## NumPy的Ndarray对象

### ndarray和list性能对比

In [4]:
import random
import time
import numpy as np

# ndarray和list的性能对比
a=[]
for i in range(10**8):
    a.append(random.random())
t1=time.time()
sum1=sum(a)
t2=time.time()

b=np.array(a)
t4=time.time()
sum3=np.sum(b) #ndarray求和
t5=time.time()

print(t2-t1,t5-t4)

1.288008689880371 0.11741089820861816


### 创建一维数组

In [ ]:

list1 = [1,2,3,4]
print(list1)
print(type(list1))

nplist1=np.array(list1)
print(nplist1)
print(type(nplist1))


In [ ]:
nplist2=np.arange(0,10,2)
print(nplist2)
print(type(nplist2))


### 创建二维数组

In [2]:
import numpy as np
list2=[[1,2],[3,4],[5,6]]
twoArray=np.array(list2)
print(list2)
print(twoArray)

#twoArray.tolist() #ndarray转换为列表

[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]


### 常用属性

In [3]:
#获取数组的维度
print(twoArray.ndim)

#形状（行，列）(0 axis, 1 axis)
print(twoArray.shape)

#元素个数
print(twoArray.size)

2
(3, 2)
6


### 调整数组形状

In [7]:
import numpy as np
nplist2 = np.array([[1, 2, 3], [4, 5, 6]])

nplist2 = nplist2.reshape(3, 2)
print(nplist2)


[[1 2]
 [3 4]
 [5 6]]


In [8]:
nplist3=nplist2.reshape((6,),order='F') #'C'以行为主展开  ‘F’以列为主展开 如果是（6，1）结果不为一维数组
nplist4=nplist2.flatten() #将多维数组转换为一维数组
print(nplist3)
print(nplist4)

[1 3 5 2 4 6]
[1 2 3 4 5 6]


In [11]:

t=np.arange(24)

t1=t.reshape(4,6)
print(f't1.shape:{t1.shape}')
print(f't1:{t1}')
print('\n')

t2=t.reshape(2,3,4)
print(f't2:{t2}')
print(f't2.shape:{t2.shape}')

t1.shape:(4, 6)
t1:[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


t2:[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
t2.shape:(2, 3, 4)


###数组转换列表

In [1]:
import numpy as np

# 创建一个ndarray数组
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("ndarray数组:")
print(arr)

# 使用tolist()方法将ndarray转换为列表
list_arr = arr.tolist()
print("\n转换后的列表:")
print(list_arr)


ndarray数组:
[[1 2 3]
 [4 5 6]]

转换后的列表:
[[1, 2, 3], [4, 5, 6]]


## NumPy的数据类型

In [1]:
import numpy as np

f=np.array([1,2,3,4,5],dtype=np.int8) #dtype设置数据类型

print(f.itemsize) # itemsize返回每个元素字节数
print(f.dtype)

# 调整数据类型
f1=f.astype(np.int16)
print(f1.dtype)

1
int8


## 数组的计算

### 数组和数的计算

In [1]:
import numpy as np

# 由于numpy的广播机制，加减乘除的值被广播到所有元素上面

t1=np.arange(24).reshape(4,6)
print(t1+2)
print('-'*20)
print(t1-2)
print('-'*20)
print(t1*2)

[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]]
--------------------
[[-2 -1  0  1  2  3]
 [ 4  5  6  7  8  9]
 [10 11 12 13 14 15]
 [16 17 18 19 20 21]]
--------------------
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]


### 数组之间的操作

In [2]:
# shape相同
t1=np.arange(0,24).reshape(6,4)
t2=np.arange(100,124).reshape(6,4)
print(t1)
print(t2)
print('-'*20)
print(t1+t2)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]


In [5]:
# 行形状相同
t1=np.arange(24).reshape(4,6)
t2=np.arange(6)
print(t1)
print(t2)
print('-'*20)
print(t1+t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
--------------------
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]]


In [7]:
# 列形状相同
t1=np.arange(24).reshape(6,4)
t2=np.arange(6).reshape(6,1)
print(t1)
print(t2)
print('-'*20)
print(t1+t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
--------------------
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]
 [25 26 27 28]]


## 轴运算

In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

print('-'*20)
print(np.sum(a,axis=0))
print('-'*20)
print(np.sum(a,axis=1))
print('-'*20)
print(np.sum(a))

[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21


In [8]:
a=np.arange(24).reshape(2,3,4)
print(a)
print('-'*20)
b=np.sum(a,axis=0)
print(b.shape)
print(b)
print('-'*20)
c=np.sum(a,axis=1)
print(c.shape)
print(c)
print('-'*20)
d=np.sum(a,axis=2)
print(d.shape)
print(d)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------
(3, 4)
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
--------------------
(2, 4)
[[12 15 18 21]
 [48 51 54 57]]
--------------------
(2, 3)
[[ 6 22 38]
 [54 70 86]]


## 数组的索引和切片

In [1]:
import numpy as np

a = np.arange(10)# 冒号分隔切片参数 start:stop:step 来进行切片操作 print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2
# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)
# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [3]:
t1=np.arange(24).reshape(4,6)
print(t1)
print('-'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('-'*20)
print(t1[1:])# 取连续的多行
print('-'*20)
print(t1[1:3,:])# 取连续的多行
print('-'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('-'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('-'*20)
print(t1[:,1])# 取一列
print('-'*20)
print(t1[:,1:])# 连续的多列
print('-'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('-'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('-'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[ 6  7  8  9 10 11]
--------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
--------------------
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[ 1  7 13 19]
--------------------
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
--------------------
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
--------------------
15
--------------------


## 数组中数值的修改

In [4]:
import numpy as np

t = np.arange( 24 ).reshape( 4, 6 )
# # 修改某一行的值
t[1, :] = 0#
# # 修改某一列的值
t[:, 1] = 0
#
# # 修改连续多行
t[1:3, :] = 0#
# # 修改连续多列
t[:, 1:4] = 0#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[0,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于 10 的值改掉
t[t < 10] = 0# print(t)
# 使用逻辑判断
# np.logical_and & # np.logical_or |
# np.logical_not ~
t[(t > 2) & (t < 6)] = 0
# 与
t[(t < 2) | (t > 6)] = 0
# 或
t[~(t > 6)] = 0
# 非
# print(t)
t=t.clip(10,18)
print(t)
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出 x，不满足输出y)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )


[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[False  True]
 [ True  True]
 [False  True]]


## 数组的添加，删除和去重

### 数组的添加

In [2]:
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# 此外，输入数组的维度必须匹配否则将生成 ValueError。
'''
参 数 说 明 ：
arr： 输 入 数 组
values：要向 arr 添加的值，需要和 arr 形状相同（除了要添加的轴）
axis：默认为 None。当 axis 无定义时，是横向加成，返回总是为一维数组！当 axis 有定义的
时候，分别为 0 和 1 的时候。当
axis 有定义的时候，分别为 0 和 1 的时候（列数要相同）。当 axis 为 1 时，数组是加在右边
（行数要相同）。
'''
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print('第一个数组')
print(a)
print('\n')

print('往数组添加元素')
print(np.append(a,[7,8,9]))
print('\n')


print('往轴0添加元素')
print(np.append(a,[[7,8,9]],axis=0)) # axis=0表示添加行
print('\n')

print('往轴1添加元素')
print(np.append(a,[[5,5,5],[7,8,9]],axis=1)) # axis=1表示添加列

第一个数组
[[1 2 3]
 [4 5 6]]


往数组添加元素
[1 2 3 4 5 6 7 8 9]


往轴0添加元素
[[1 2 3]
 [4 5 6]
 [7 8 9]]


往轴1添加元素
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [3]:
# 2. numpy.insert
# 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

a=np.array([[1,2],[3,4],[5,6]])
print('第一个数组')
print(a)
print('\n')

print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print('沿轴 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')
print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))


第一个数组
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


### 数组的删除

In [6]:
#numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''
参 数 说 明 ：
arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
'''
a = np.arange(12).reshape(3,4)
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')
print('删除第一行：')
print(np.delete(a,0,axis = 0))
print('\n')
print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')


第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除第一行：
[[ 0  1  2  3]
 [ 8  9 10 11]]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




### 数组的去重

In [7]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展开
return_index：如果为 true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为 true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为 true，返回去重数组中的元素在原数组中的出现次数
'''
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('第一个数组：')
print (a)
print ('\n')
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


## numpy的计算（数学函数）

In [ ]:
import numpy as np
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
# 1.获取所有数据最大值
result = np.max(score)
print(f'所有数据最大值：{result}')
# 2.获取某一个轴上的最大值
result = np.max(score, axis=0)
print(f'0轴上的最大值：{result}')
result = np.max(score, axis=1)
print(f'1轴上的最大值：{result}')
# 3.获取所有数据最小值
result = np.min(score)
print(f'所有数据最小值：{result}')
# 4.获取某一个轴上的最小值
result = np.min(score, axis=0)
print(f'0轴上的最小值：{result}')
result = np.min(score, axis=1)
print(f'1轴上的最小值：{result}')
# 5.数据的比较
result = np.maximum( [-2, -1, 0, 1, 2], 0 )
# 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum( [-2, -1, 0, 1, 2], 0 )
# 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum( [-2, -1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result)# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；
# 6.数据的平均值
result = np.mean(score)
print(f'所有数据的平均值：{result}')
result = np.mean(score,axis=0)
# 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
'''
[1, 2, 3]------> |1 |2 |3 |
[4, 5, 6]------> |5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(1))
'''
[1, 2, 3]------> |1 |2+1 |3+2+1 |
[4, 5, 6]------> |4 |4+5 |4+5+6 |
'''
# 8. argmin 求最小值索引
result = np.argmin(score,axis=0)
res=np.min(score,axis=0)
#这样我们就可以知道最小的 81 是第二排的，是从前往后遍历的
print(result,res)
# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)
# 10. 极 值
result = np.ptp(score,axis=None)#就是最大值和最小值的差
print(result)
# 拓展：方差 var, 协方差 cov, 计算平均值 average, 计算中位数 median

'''通用函数：
numpy.sqrt(array) 平方根函数
numpy.exp(array) e^array[i]的数组
numpy.abs/fabs(array) 计算绝对值
numpy.square(array) 计算各元素的平方 等于 array 2
numpy.log/log10/log2(array) 计算各元素的各种对数
numpy.sign(array) 计算各元素正负号
numpy.isnan(array) 计算各元素是否为 NaN
numpy.isinf(array) 计算各元素是否为 NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array) 将 array 中值得整数和小数分离，作两个数组返回
numpy.ceil(array) 向上取整,也就是取比这个数大的整数
numpy.floor(array) 向下取整,也就是取比这个数小的整数
numpy.rint(array) 四舍五入
numpy.trunc(array) 向 0 取整
numpy.cos(array) 正弦值
numpy.sin(array) 余弦值
numpy.tan(array) 正切值
numpy.add(array1,array2) 元素级加法
numpy.subtract(array1,array2) 元素级减法
numpy.multiply(array1,array2) 元素级乘法
numpy.divide(array1,array2) 元素级除法 array1./array2
numpy.power(array1,array2) 元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2) 元素级最大值，忽略 NaN
numpy.mod(array1,array2) 元素级求模
numpy.copysign(array1,array2) 将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''


## 数组的拼接与分割

### 数组的拼接

In [2]:
import numpy as np
# 1. 根据轴连接的数组序列
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# 要求 a,b 两个数组的维度相同
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))

# 2. 根据轴进行堆叠
print ('沿轴 0 堆叠两个数组：')
print (np.stack((a,b),axis= 0))
print ('\n')
print ('沿轴 1 堆叠两个数组：')
print (np.stack((a,b),axis = 1))

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]
沿轴 0 连接两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 连接两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### 分割

In [3]:
# 1. 将一个数组分割为多个子数组
'''
参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置
（左开右闭）
axis：沿着哪个维度进行切向，默认为 0，横向切分。为 1 时，纵向切分
'''
import numpy as np
arr = np.arange(9).reshape(3,3)
print ('将数组分为三个大小相等的子数组：')
b = np.split(arr,3)
print (b)
# 2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
harr = np.floor(10*np.random.random((2, 6)))
print ('原 array：')
print(harr)
print ('拆分后：')
print(np.hsplit(harr, 3))
# 3.numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4,4)
print ('第一个数组：')
print (a)
print ('\n')
print ('竖直分割：')
b = np.vsplit(a,2)
print (b)


将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
原 array：
[[8. 9. 4. 1. 6. 5.]
 [7. 4. 7. 4. 3. 6.]]
拆分后：
[array([[8., 9.],
       [7., 4.]]), array([[4., 1.],
       [7., 4.]]), array([[6., 5.],
       [3., 6.]])]
第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## 数组中nan和inf

In [6]:
'''
C 语言中表示最大的正整数值是 0x7FFF FFFF，最小的负整数是 0x8000 0000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有
float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现 inf 呢？ 比如一个数字除以 0，Python 中会报错，但是 numpy 中会是一个
inf
或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。
任何与其做运算结果都是 nan（比如零除以零，在 numpy 中）
'''
import numpy as np

# 创建一个 nan 和 inf #
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))

# np.nan!=np.nan
print(np.nan==np.nan)

# nan和任何值计算都为nan
print(np.nan+1)

# --判断数组中为 nan 的个数
t = np.arange(24,dtype=float).reshape(4,6)
# 将三行四列的数改成 nan
t[3,4] = np.nan
t[2,3] = np.nan
print(t)
print(t!=t)
# 可以使用 np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))
# 并 且 np.nan != np.nan 结果 是 TRUE
# 所以我们可以使用这两个结合使用判断 nan 的个数
print(np.count_nonzero(t != t))
# 将 nan 替换为 0
t[np.isnan(t)] = 0
print(t)



nan <class 'float'>
inf <class 'float'>
False
nan
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. nan 16. 17.]
 [18. 19. 20. 21. nan 23.]]
[[False False False False False False]
 [False False False False False False]
 [False False False  True False False]
 [False False False False  True False]]
23
2
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14.  0. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]
